spring:
  config:
    import:
      - optional:classpath:application-kafka.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  mongodb:
    uri: ${MONGO_URL}

logging:
  level:
    root: info

market:
  kis:
    base-url: ${KIS_BASE_URL:https://openapi.koreainvestment.com:9443}
    user-id: ${KIS_USER_ID}
    credentials:
      - app-key: ${KIS_API_KEY}
        app-secret: ${KIS_API_SECRET}
      - app-key: ${KIS_API_KEY_2:}
        app-secret: ${KIS_API_SECRET_2:}
      - app-key: ${KIS_API_KEY_3:}
        app-secret: ${KIS_API_SECRET_3:}
    websocket:
      url: ${KIS_WEBSOCKET_URL:ws://ops.koreainvestment.com:21000}

security:
  jwt:
    hmac-secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /doc/investment/swagger-ui.html
  api-docs:
    path: /doc/investment/v3/api-docs
